---
title: "Bootcamp3"
author: "Chase Rowe"
date: "8/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(dplyr)
```

# Module 6

```{r}
gap = read.csv("data/gapminder-FiveYearData.csv")
head(gap)
```

```{r}
# median lifexp for each continent
LE_bycontinent <- gap %>%
  group_by(continent) %>%
  summarize(medLE = median(lifeExp))
head(LE_bycontinent)

# new gap col has total pop of continent per observation
pop_gap <- gap %>%
  group_by(continent, year) %>%
  mutate(cont_pop = sum(pop))
head(pop_gap)

#new col shows deviance from continent gdpPercap
dev_gap <- gap %>%
  group_by(continent, year) %>%
  mutate(dev = gdpPercap - mean(gdpPercap)) %>%
  arrange(desc(dev))
head(dev_gap)
```

# Module 7

```{r}
gap %>% ggplot(aes(x=lifeExp)) + geom_histogram(binwidth=5)

pl = ggplot(gap, aes(x=pop,y=gdpPercap)) + geom_point() + scale_x_log10()

pl = pl + ggtitle("GDP Per Capita by Population") + xlab("Population") + ylab("GDP Per Capita") + theme_minimal()
pl

# trellis plot, lifeExp by gdpPercap, one subplot per continent (2x3)
ggplot(gap, aes(x=gdpPercap, y=lifeExp)) + geom_point(aes(size=pop)) + 
  facet_wrap(~continent,nrow=2,ncol=3) + scale_x_continuous(limits=c(100,50000))

gap %>% mutate(binGdp = cut(gdpPercap, breaks=5)) %>%
  ggplot(aes(x=binGdp, y=lifeExp)) + geom_boxplot()
```

