---
title: "Bootcamp1"
author: "Chase Rowe"
date: "8/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Part 1

```{r}
getwd()
gap = read.csv('data/gapminder-FiveYearData.csv',
               stringsAsFactors=F)
head(gap)
```

```{r}
x <- mean(gap$lifeExp)

print(round(x, digits=2))
print(signif(x, digits=2))

gap$gdpPcEuro <- gap$gdpPercap/1.17

gap$totalGdp <- gap$gdpPercap * gap$pop
trill <- gap$totalGdp > 1e12
```

```{r}
wealthiest <- gap$gdpPercap[trill]

gap$gdpPercap[gap$gdpPercap > 40000] = 40000
plot(gap$lifeExp, gap$gdpPercap)
```

```{r}
hist(gap$lifeExp[gap$year == 2007], breaks=35)
```

```{r}
life = gap$lifeExp[gap$year == 2007]
gdp = gap$gdpPercap[gap$year == 2007]
plot(gdp ~ life)
```

# Part 2

```{r}
ls()
```

```{r}
setwd("C:/Users/Me/Desktop")
write.csv(cpds, file='data', quote=F, row.names=F)
```

```{r}
pdf("C:/Users/Me/Desktop/gapplot_small.pdf", width=10, height=10)
plot(gap$pop ~ gap$gdpPercap)
pdf("C:/Users/Me/Desktop/gapplot_big.pdf", width=1000, height=1000)
plot(gap$pop ~ gap$gdpPercap)
dev.off()
```

# Part 3

```{r}
row5 <- gap[5,]

lastrow <- tail(gap,1)

bigGdp <- sum(gap$gdpPercap > 50000)

gap2 <- gap
gap2$gdpPercap[gap2$gdpPercap > 50000] <- NA

print(paste(gap2[1,]['country'], gap2[1,]['year'], sep="-"))
```

```{r}
print_dim <- function(df) {
  rows <- dim(df)[1]
  result <- paste("There are", rows, "rows in the dataset.")
  return(result)
}
result <- print_dim(gap)

tail(gap,1)

vec <- gap$lifeExp > 75 & gap$gdpPercap < 10000
sum(vec)/dim(gap)[1]

# vec gives bool for above logic on rows
gap[vec,]

paste("Gap is of type", class(attributes(gap)), sep=" ")
# note: sep=" " is default so above arg is redundant
```

